### PR TITLE
Get rid of pageInfo

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin

### CODE REVIEW

**Comment by inikulin** [comment]
Why major version bump?

**Comment by AndreyBelym** [comment]
Sorry, I've changed version to 1.3.0

**Comment by AndreyBelym** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
FYI: rebase required

**Comment by inikulin** [comment]
wow, I thought it's already merged

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
