### PR TITLE
Change compiler API to fit new master-compiler protocol

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @churkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
Tests are failed, fix please

**Comment by inikulin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Pull request merged**
